### ISSUE TITLE
Connection error on download

### ISSUE THREAD

**Issue by carolinasolfernandez** [amazon-science/siam-mot#58]
I'm trying to run demos/demo.py but returns connection error after a while. I think that the model links are not working anymore

```
Downloading: "http://dl.yf.io/dla/models/imagenet/dla34-ba72cf86.pth" to C:\Users\xxxxx/.cache\torch\hub\checkpoints\dla34-ba72cf86.pth
Traceback (most recent call last):
  File "C:\Users\caros\anaconda3\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\caros\anaconda3\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\caros\anaconda3\lib\http\client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\caros\anaconda3\lib\http\client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\caros\anaconda3\lib\http\client.py", line 1040, in _send_output
    self.send(msg)
  File "C:\Users\caros\anaconda3\lib\http\client.py", line 980, in send
    self.connect()
  File "C:\Users\caros\anaconda3\lib\http\client.py", line 946, in connect
    self.sock = self._create_connection(
  File "C:\Users\caros\anaconda3\lib\socket.py", line 844, in create_connection
    raise err
  File "C:\Users\caros\anaconda3\lib\socket.py", line 832, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

**Comment by bingshuai2019** [comment]
Hi, the demo model artifact is still downloadable (e.f. for person model, you can manually download it here: https://aws-cv-sci-motion-public.s3.us-west-2.amazonaws.com/SiamMOT/demo_models/person.zip)
